### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by mamat-rahmat** [olimpiadeinformatika/solinfo#1]
Solinfo is a web where we can put programming problems description along with the solutions. Problem descriptions are public but the solutions are private-only. User can register and pay for premium account to see private solutions.

## Other Functional Requirements

- Problem description and solution editor should support markdown for easy editing and latex for mathematical expression
- Problems can have category and tag for easy searching suitable problem. Category is the source of problem (e.g. online judge name or competition name) while tags are tipe of solution of problem (eg : dynamic-programming, greedy)

## TODO

- [ ] Create initial project using Heroku template
- [ ] Deploy to Heroku Free Plan
- [ ] Create problems model
